__Linear Regression Using Normal Equation__

In [1]:
import numpy as np

In [ ]:
# Test case from DeepML

X = [[1, 1], [1, 2], [1, 3]], 
y = [1, 2, 3]

In [ ]:
# Passing them into Numpy array format

X = np.array(X).squeeze()
y = np.array(y)

print(X.shape, y.shape)
print(y)
print(X)

(3, 2) (3,)
[1 2 3]
[[1 1]
 [1 2]
 [1 3]]


In [27]:
for i in range(X.shape[0]):
    print(X[i])

[1 1]
[1 2]
[1 3]


In [57]:
# Removing bias column and treating this as simple linear regression 

X = X[:, 1]

In [66]:
''' 
For calculating slope and intercept we need to implement following equation:

    m = (Σ(X - X̄)(Y - Ȳ)) / (Σ(X - X̄)²)
    c = Ȳ - mX̄

And we need to run those equations for every data point and then can be achieved through loop 

'''

class LinearRegression:

    def __init__(self):

        self.coef_ = None
        self.intercept_ = None 

    def fit(self, X, y):

        X_mean = X.mean()
        y_mean = y.mean()

        num = 0
        den = 0

        for i in range(X.shape[0]):
            num = num + (X[i] - X_mean) * (y[i] - y_mean)
            den = den + (X[i] - X_mean) * (X[i] - X_mean)

        self.coef_ = num/den
        self.intercept_ = y.mean() - (self.coef_ * X.mean())

        return self.intercept_, self.coef_
    

In [71]:
lr = LinearRegression()
list(lr.fit(X, y))

[0.0, 1.0]

-----

In [ ]:
# __Now considering that bias columns__

X = [[1, 1], [1, 2], [1, 3]], 
y = [1, 2, 3]

In [75]:
np.array(X).squeeze().shape

(3, 2)

### Normal Equation (Multilinear Regression)

The coefficients are computed as $\theta = (X^\top X)^{-1} X^\top y$.


In [ ]:
# writting for DeepML
def linear_regression_normal_equation(X: list[list[float]], y: list[float]) -> list[float]:

	''' 
	In this case we are gonna implement above formula 
	 '''

	X = np.array(X).squeeze()
	y = np.array(y)

	theta = np.linalg.inv(np.dot(X.T, X)).dot(X.T).dot(y)

	return np.round(theta, 4)

In [91]:
linear_regression_normal_equation(X, y)

array([-0.,  1.])

----